file_format: "1"
id: esper_v3
name: esper v3
type: shield
url: https://github.com/trentslutzky/zmk-config
requires: [pro_micro]
exposes: []
features:
  - keys
siblings:
  - esper_v3_left
  - esper_v3_right
