file_format: "1"
id: esper_v4
name: esper v4
type: shield
url: https://github.com/trentslutzky/zmk-config
requires: [pro_micro]
exposes: []
features:
  - keys
siblings:
  - esper_v4_left
  - esper_v4_right
  - esper_v4_dongle
